FROM arm64v8/node:24-slim

WORKDIR /app/

COPY package*.json ./

RUN npm install --omit=dev

COPY *.js ./

EXPOSE 9229

# Persist credentials directory
RUN mkdir -p /app/data && chown node:node /app/data

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
